config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)
	
  resources :breeds, only: :show
	resources :horses, only: :show do
		collection do
			get 'search_results'
		end
	end

  root to: 'breeds#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
# frozen_string_literal: true

class Breed < ApplicationRecord
  has_many :horses

  validates :name, presence: true
end

app/models/horse.rb
class Horse < ApplicationRecord
  belongs_to :breed

	validates :name, presence: true
	
	has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breeds_controller.rb
# frozen_string_literal: true

class BreedsController < ApplicationController
  # GET /
  def index
    @breeds = Breed.order(:name)
  end

  # GET /breeds/:id
  def show
    @breed = Breed.find(params[:id])
  end
end

app/controllers/horses_controller.rb
# frozen_string_literal: true

class HorsesController < ApplicationController
  # GET /horses/:id
  def show
    @horse = Horse.find(params[:id])
	end
	
	def search_results
		@query = params[:query]
		@horses = Horse.where('name LIKE ?', "%#{@query}%")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/views/breeds/index.html.erb
<h3 class="title is-4">All Horse Breeds</h3>

<p>
<% @breeds.each do |breed| %>
  <%= link_to breed.name, breed, class: "button is-link" %>
<% end %>
</p>

app/views/breeds/show.html.erb
<h3 class="title is-4"><%= @breed.name %></h3>
<h4 class="subtitle is-5">Horses of this breed</h4>

<div class="columns is-multiline">
	<% @breed.horses.each do |horse| %>
		<%= render partial: 'horses/horse',
							collection: @breed.horses,
							locals: { name_is_link: true } %>
	<% end %>
</div>

app/views/horses/_horse.html.erb
<div class="column is-one-third">
	<% if horse.image.present? %>
		<div class="card-image">
				<figure class="image is-4by3">
					<%= image_tag horse.image %>
				</figure>
		</div>
	<% end %>
	<div class="card horse">
		<div class="card-content">
			<p class="title is-4">
				<% if name_is_link %>
					<%= link_to horse.name, horse %>
				<% else %>
					<%= horse.name %>
				<% end %>
			</p> 
			<ul>
				<li>
					<strong>Age:</strong> <%= horse.age%>
				</li>
				<li>
					<strong>Number Of Legs:</strong> <%= horse.number_of_legs %>
				</li>
				<li>
					<strong>Top Speed:</strong> <%= horse.top_speed %>
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/horses/search_results.html.erb
<p>
	Your search for '<%= @query %>' returned <%= pluralize(@horses.size,'result') %>.
</p>

<div class="columns is-multiline">
	<%= render partial:'horse',
						 collection: @horses,
						 locals: {name_is_link: true} %>
</div>

app/views/horses/show.html.erb
<%= render partial: 'horse',
					 object: @horse,
					locals: { name_is_link: false }  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HorsesOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
		<meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
  </head>

  <body>
	<section class="section">
    <h1 class="title"><%= link_to 'Horses on Rails', root_path %></h1>
    <h2 class="subtitle">Look at all the pretty horses standing in a <strong>row, row, row</strong>.</h2>
		<%= form_with(url: search_results_horses_path, method: "get",local: true) do %>
			<%= label_tag(:query, "Search for:") %>
			<%= text_field_tag(:query) %>
			<%= submit_tag("Search") %>
		<% end %>
	</section>
	<section class="section">
    <%= yield %>
	</section>
  </body>
</html>